\input texinfo @c -*-texinfo-*-

@settitle SWISH Installer Manual
@include my-bib-macros.texi
@mybibuselist{References}
@paragraphindent none

@c DOCUMENT LICENSE FOLLOWS.
@copying
Copyright @copyright{} 2016-2017 Franco Masotti @email{franco.masotti@@student.unife.it}

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end copying

@titlepage
@title SWISH Installer Documentation
@author Franco Masotti
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top SWISH Installer

This manual is for SWISH Installer.

@menu
* Description::                         A brief description of what this is all about
* Demonstrations::                      Public available example websites
* Available packages and descriptions:: Table of available packages for each system and their descriptions
* Installation::                        Installation procedures on various systems
* Components download::                 Components to be downloaded after the installation
* Daemons management::                  How to start, stop and enable the daemons
* Accessing the server::                How to access and use the servers
* Development::                         A thorough description on how to develop over this installer
* Thanks::                              People and communities
* @mybibnode{}::                        References to the technologies used
@end menu
@end ifnottex

@c ----
@c ----
@c ----
@c ----

@node Description
@chapter About
@c index test
@section About
The purpose of this repository is to handle the creation 
of serveral packages and helpers in order to
install Cplint@footnote{@mybibcite{Cplint}}
on SWISH@footnote{@mybibcite{SWISH}}
with an Rserve@footnote{@mybibcite{Rserve}} environment,
as well as the "vanilla" version of SWISH.

SWISH relies on SWI Prolog@footnote{@mybibcite{Swipl}}, 
a prolog interpteter.

@image{swish-screenshot}

@image{swish-cplint-screenshot}

@image{swish-cplint-systemd-screenshot}

@subsection Terminology

In order to understand this documentation correctly some terminology used here 
must be explained.

@code{<} and @code{>} means pseudocode.

@code{#} means that the command must be executed by @code{root}.

@code{$} means that the command must be executed by the current user.

@subsection Directory listings

When you see something like the following, it represents a directory listing of
the first named (head) directory. These representations are generated from 
@command{$ tree --charset=ascii -d <dirname>}.

@example
common/
|-- rserve-sandbox
|-- swish
`-- swish-cplint
@end example

@c ----
@c ----
@c ----
@c ----

@node Demonstrations
@chapter Demonstrations
If you want to see how the final result might look like, have a look at
@uref{http://cplint.lamping.unife.it/} for Cplint on SWISH
and @uref{http://swish.swi-prolog.org/} for the "vanilla" version of SWISH.

@c ----
@c ----
@c ----
@c ----

@node Available packages and descriptions
@chapter Available packages and descriptions
@section Available packages

@multitable @columnfractions .166 .166 .166 .166 .166 .166
@headitem Distributions
@tab SWISH 
@tab Cplint on SWISH 
@tab Cplint on SWISH binary
@tab Rserve sandbox
@tab Rserve sandbox binary
@item Arch Linux
@tab @code{swish}
@tab @code{swish-cplint}
@tab @code{swish-cplint-bin}
@tab @code{rserve-sandbox-docker}
@tab @code{rserve-sandbox-docker-bin}
@item Debian
@tab @code{-}
@tab @code{-}
@tab @code{-}
@tab @code{rserve-sandbox-docker}
@tab @code{-}
@end multitable

@section Descriptions

The following terms will be used throughout the document to identify the 
packages in a generic manner (non-distribution specific).

@multitable @columnfractions .166 .166 .166 .166 .166 .166
@headitem -
@tab SWISH 
@tab Cplint on SWISH 
@tab Cplint on SWISH binary
@tab Rserve sandbox
@tab Rserve sandbox binary
@item Description
@tab the vanilla version of SWISH
@tab SWISH with the Cplint suite. Uses Rserve sandbox as a main dependency
@tab precompiled version of Cplint on SWISH. Uses Rserve sandbox binary as well as precompiled web components
@tab an R environment running inside a docker container
@tab precompiled version of Rserve sandbox
@end multitable

@c ----
@c ----
@c ----
@c ----

@node Installation
@chapter Installation
@section Arch Linux
There at least two possibilities to install the packages.

@subsection Using an AUR helper

Yaourt@footnote{@mybibcite{Yaourt}} is among the most popular 
AUR@footnote{@mybibcite{AUR}}
helpers available. The following 
command@footnote{@mybibcite{Packages on the AUR}}
will install all the dependencies automatically.
Use the package names described in the
@ref{Available packages and descriptions, , Available packages}
section.

@verbatim
$ yaourt -Sa s <package name> --noconfirm
@end verbatim

@quotation Note
When you install Yaourt on
Parabola GNU/Linux-libre@footnote{@mybibcite{Parabola}}
you will be asked to remove @code{your-freedom}.
@end quotation

@subsection Without using an AUR helper
Adapt this command to match the to be installed package:

@verbatim
$ wget "https://aur.archlinux.org/cgit/\
aur.git/snapshot/<package name>.tar.gz"
$ tar -zxvf <package name>.tar.gz
$ cd <package name>
$ makepkg -sri --noconfirm
@end verbatim

@subsubsection Cplint on SWISH
@itemize @bullet
@item
Install @code{swi-prolog-devel}

@item
Install @code{rserve-sandbox-docker}

@item
Install @code{swish-cplint}

@end itemize

@subsubsection Cplint on SWISH binary
@itemize @bullet
@item
Install @code{swi-prolog-devel}

@item
Install @code{rserve-sandbox-docker-bin}

@item
Install @code{swish-cplint-bin}

@end itemize

@subsubsection SWISH
@itemize @bullet
@item
Install @code{swish}

@end itemize

@subsection Daemons management
Arch Linux and derivative distros use 
Systemd@footnote{@mybibcite{systemd}} as the 
init system. First see @ref{Components download} and then
see @ref{Daemons management}.

@section Debian
TODO

@c ----
@c ----
@c ----
@c ----

@node Components download
@chapter Components download
This section only applies to Cplint on SWISH and Cplint on SWISH binary.

Before running the daemons some components must be downloaded.
The first thing to do is to start
Docker@footnote{@mybibcite{Docker}} manually.
See @ref{Daemons management} for more information.

@section Rserve sandbox and Rserve sandbox binary
To download the Docker image file as well as all dependencies
for R@footnote{@mybibcite{R}}, or to load the docker image,
run the following command:
@verbatim
$ sudo -u rsd rserve-sandbox-docker -i
@end verbatim

@section Cplint on SWISH and Cplint on SWISH binary
Before reading on, start the Rserve sandbox service, to avoid errors
on some prolog tests executed by the Cplint R library.

To download all the prolog packages necessary in order to run
Cplint on SWISH correcly:
@verbatim
$ sudo -u swish swish-cplint -i
@end verbatim

@c ----
@c ----
@c ----
@c ----

@node Daemons management
@chapter Daemons management
Commands to manage the daemons depend on the init system in use.

@section Systemd
@subsection Cplint on SWISH
Docker is a dependency which must be started manually during the setup.
@verbatim
# systemctl start docker
@end verbatim

The following command will run @code{swish-cplint} as well as
@code{rserve-sandbox-docker} as its dependency:
@verbatim
# systemctl start swish-cplint
@end verbatim

To start @code{swish-cplint} and @code{rserve-sandbox-docker} at boot:
@verbatim
# systemctl enable swish-cplint
@end verbatim

You can stop both services with:
@verbatim
# systemctl stop swish-cplint
# systemctl stop rserve-sandbox-docker
@end verbatim

@quotation Note
stopping @code{swish-cplint}
does not imply that @code{rserve-sandbox-docker}
will be stopped.
@end quotation

To check the status of both daemons:
@verbatim
# systemctl status swish-cplint
# systemctl status rserve-sandbox-docker
@end verbatim

@subsection Cplint on SWISH binary
For simplicity, services names do not change, so the
same instructions of Cplint on SWISH are also applicable here.

@subsection SWISH
Running and managing SWISH alone is very similar to the 
previous method: instead of using @command{swish-cplint} 
as part of the commands, you must use @command{swish}. 
You don't need to worry about Rserve or Docker.

@c ----
@c ----
@c ----
@c ----

@node Accessing the server
@chapter Accessing the server
To access the web interface you need a
JavaScript @footnote{@mybibcite{JavaScript}}
enabled browser and you have to connect to port 3050.
For example: @code{http://localhost:3050} or @code{http://127.0.0.1:3050}

@c ----
@c ----
@c ----
@c ----

@node Development
@chapter Development
@section Repository structure

@verbatim
.
|-- common
|   |-- rserve-sandbox-docker
|   |-- rserve-sandbox-docker-bin
|   |-- swish
|   |-- swish-cplint
|   `-- swish-cplint-bin -> swish-cplint/
`-- distributions
    |-- archLinux-based
    |   |-- dest
    |   |-- packages
    |   |   |-- rserve-sandbox-docker
    |   |   |-- rserve-sandbox-docker-bin
    |   |   |-- swish
    |   |   |-- swish-cplint
    |   |   `-- swish-cplint-bin
    |   `-- test
    `-- debian-based
@end verbatim

The @file{distributions} directory contains all the files useful to
build packages for a specific distribution. Makefiles
are used to achieve this.

The @file{common} directory contains all the files which
are not distribution specific.

@subsection Distribution-specific files
@xref{Development, ,Building the packages}

@subsection Common files

@verbatim
common/
|-- rserve-sandbox-docker
|   `-- run.sh
|-- rserve-sandbox-docker-bin
|   `-- run.sh -> ../rserve-sandbox-docker/run.sh
|-- shared_functions.sh
|-- swish
|   |-- run.pl
|   `-- run.sh
|-- swish-cplint
|   |-- install_web_iface_deps.pl
|   |-- run.pl
|   `-- run.sh
`-- swish-cplint-bin -> swish-cplint/
@end verbatim

The @file{run.sh} files are helpers to start and stop the daemons.
These helpers should work on any distribution. You can 
edit the variables at the top of each file accordingly.

The @file{run.pl} files are a modified version
of the original files with the same name. These have been
created in order to lauch SWISH as a background program.
Without the changes contained in those files, you couldn't
run SWISH in the background.

Another important file is @file{shared_functions.sh}
which contains all common functions for the @file{run.sh}
files. It must be appended to every @file{run.sh}, within
a Makefile for example with the following:

@example
$ cat shared_functions.sh >> @{rserve-sandbox*,swish,swish-cplint@}/run.sh
@end example

Cplint on SWISH and Cplint on SWISH binary contain a post installation script 
called @file{install_web_iface_deps.pl}. This script, called by
@file{run.sh}, simply installs all the necessary Prolog
dependencies automatically.

@section Guidelines to create packages
Makefiles are used to build the package in a new directory
by copying all necessary files (also from
the @file{common} directory). Each Makefile is
distribution-based specific.

You will read general information about the packages,
all their install and remove actions and how to build
your version of the modified packages.

Installation and removal actions must be done sequentially.

@c ----
@c ----
@c ----
@c ----

@subsection Rserve sandbox
@subsubsection General information
@itemize @bullet

@item
Data directory

@file{/usr/share/rserve-sandbox-docker}

@item
Dependencies
@itemize @minus
@item
GNU Bash@footnote{@mybibcite{GNU Bash}}

@item
GNU Make@footnote{@mybibcite{GNU Make}}

@item
Gawk@footnote{@mybibcite{Gawk}}

@item
Docker

@item
R
@end itemize

@end itemize

@subsubsection Install actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
None
@end itemize

@item
During

@itemize @minus
@item
Make a symbolic link to be able to call 
@file{rserve-sandbox-docker} from @file{/usr/bin}

@verbatim
$ ln -s /usr/share/rserve-sandbox-docker/run.sh \
/usr/bin/rserve-sandbox-docker
@end verbatim
@end itemize

@item
Post

@itemize @minus
@item
Add @code{rserve} user and group.

@verbatim
# getent group rserve 1>/dev/null 2>/dev/null \
    || groupadd -g 32749 -r rserve >/dev/null
# getent passwd rserve 1>/dev/null 2>/dev/null \
    || useradd -u 32749 -m -d /home/rserve \
    -s /bin/false -r -g rserve rserve >/dev/null
# chmod 750 /home/rserve
@end verbatim

@item
Add @code{rsd} user and group.

@verbatim
# getent group rsd 1>/dev/null 2>/dev/null \
    || groupadd -r rsd >/dev/null
# getent passwd rsd 1>/dev/null 2>/dev/null \
    || useradd -s /bin/false -r -g rsd rsd >/dev/null
@end verbatim

@item
Add the new user to the @code{docker} group

@verbatim
# gpasswd -a rsd docker >/dev/null
@end verbatim

@item
Change ownership of the package data directory

@verbatim
# chown -R rsd:rsd /usr/share/rserve-sandbox-docker
@end verbatim

@end itemize

@quotation Note
the @code{rsd} user and group was created in order to avoid privilege 
escalation, since any user which belongs to the @code{docker} group is
equivalent to @code{root}@footnote{@mybibcite{Docker root privileges}}.
@end quotation

@end itemize

@subsubsection Remove actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
None
@end itemize

@item
During

@itemize @minus
@item
None
@end itemize

@item
Post

@itemize @minus
@item
Tell the user that @file{/home/rserve}, @code{rsd} user 
and group, @code{rserve} user and group 
and all the Docker files can be removed (this depends 
on the package remove policies of the chosen distro).

@end itemize

@end itemize

@c ----
@c ----
@c ----
@c ----

@subsection Rserve sandbox binary
@itemize @bullet
@item
Same as Rserve sandbox.
@end itemize

@c ----
@c ----
@c ----
@c ----

@subsection Cplint on SWISH
@subsubsection General information
@itemize @bullet
@item
Data directory

@file{/usr/share/swish-cplint}

@item
Dependencies
@itemize @minus
@item
Bower (make dependency)@footnote{@mybibcite{Bower}}

@item
GNU Bash

@item
GNU Make (make dependency)

@item
Gawk

@item
Git@footnote{@mybibcite{Git}}

@item
Graphviz@footnote{@mybibcite{Graphviz}}

@item
libXinerama@footnote{@mybibcite{libXinerama}}

@item
libXpm@footnote{@mybibcite{libXpm}}

@item
Rserve sandbox

@item
SWI Prolog (development version)
@end itemize

@end itemize

@subsubsection Install actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
Compile the web dependencies

@verbatim
$ bower --allow-root install
$ make src
@end verbatim

@item
Copy @file{run.pl}, @file{run.sh} and
@file{install_web_iface_deps.pl} in SWISH's root directory.
@end itemize

@item
During

@itemize @minus
@item
Make a symlink to be able to call 
@file{swish-cplint} from @file{/usr/bin}

@verbatim
$ ln -s /usr/share/swish-cplint/run.sh /usr/bin/swish-cplint
@end verbatim

@end itemize

@item
Post

@itemize @minus
@item
Add @code{swish} user and group

@verbatim
# getent group swish 1>/dev/null 2>/dev/null \
    || groupadd -r swish >/dev/null
# getent passwd swish 1>/dev/null 2>/dev/null \
    || useradd -m -d /home/swish -r -g swish swish >/dev/null
@end verbatim

@item
Add @code{swish} user to the previously created @code{rserve}
group.

@verbatim
# gpasswd -a swish rserve >/dev/null
@end verbatim

@item
Change ownership of the package data directory

@verbatim
# chown -R swish:swish /usr/share/swish-cplint
@end verbatim

@end itemize

@end itemize

@subsubsection Remove actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
None
@end itemize

@item
During

@itemize @minus
@item
None
@end itemize

@item
Post

@itemize @minus
@item
Tell the user that @file{/home/swish} and @code{swish} user 
and group can be removed (this depends on the package 
remove policies of the chosen distro).

@end itemize

@end itemize

@c ----
@c ----
@c ----
@c ----

@subsection Cplint on SWISH binary
@subsubsection General information
@itemize @bullet
@item
Data directory

@file{/usr/share/swish}

@item
Dependencies
@itemize @minus
@item
curl (make dependency)@footnote{@mybibcite{curl}}

@item
GNU Bash

@item
Gawk

@item
Git

@item
Graphviz

@item
libXinerama

@item
libXpm

@item
Rserve sandbox binary

@item
SWI Prolog (development version)

@item
UnZip (make dependency)@footnote{@mybibcite{UnZip}}
@end itemize

@end itemize

@subsubsection Install actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
Download and unzip the web dependencies

@verbatim
$ curl -o swish-bower-components.zip \
http://www.swi-prolog.org/download/swish/swish-bower-components.zip
$ unzip swish-bower-components.zip
$ rm -rf swish-bower-components.zip
@end verbatim

@item
Copy @file{run.pl}, @file{run.sh} and
@file{install_web_iface_deps.pl} in SWISH's root directory.
@end itemize

@end itemize

@itemize @bullet
@item
During

@itemize @minus
@item
Same as Cplint on SWISH
@end itemize

@end itemize

@itemize @bullet
@item
Post

@itemize @minus
@item
Same as Cplint on SWISH
@end itemize

@end itemize

@subsubsection Remove actions
@itemize @bullet
@item
Same as Cplint on SWISH
@end itemize

@c ----
@c ----
@c ----
@c ----

@subsection SWISH
@subsubsection General information
@itemize @bullet
@item
Data directory

@file{/usr/share/swish}

@item
Dependencies
@itemize @minus
@item
Bower (make dependency)

@item
GNU Bash

@item
GNU Make (make dependency)

@item
Gawk

@item
libXinerama

@item
libXpm

@item
SWI Prolog (development version)
@end itemize

@end itemize

@subsubsection Install actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
Compile the web dependencies

@verbatim
$ bower --allow-root install
$ make src
@end verbatim

@item
Copy @file{run.pl} and @file{run.sh} and in SWISH's
root directory.
@end itemize

@item
During

@itemize @minus
@item
Make a symlink to be able to call 
@file{swish} from @file{/usr/bin}

@verbatim
$ ln -s /usr/share/swish/run.sh /usr/bin/swish
@end verbatim

@end itemize

@item
Post

@itemize @minus
@item
Add @code{swish} user and group

@verbatim
# getent group swish 1>/dev/null 2>/dev/null \
    || groupadd -r swish >/dev/null
# getent passwd swish 1>/dev/null 2>/dev/null \
    || useradd -m -d /home/swish -r -g swish swish >/dev/null
@end verbatim

@item
Change ownership of the package data directory

@verbatim
# chown -R swish:swish /usr/share/swish
@end verbatim

@end itemize

@end itemize

@subsubsection Remove actions
@itemize @bullet
@item
Pre

@itemize @minus
@item
None
@end itemize

@item
During

@itemize @minus
@item
None
@end itemize

@item
Post

@itemize @minus
@item
Tell the user that @file{/home/swish} and @code{swish} user 
and group can be removed (this depends on the package 
remove policies of the chosen distro).
@end itemize

@end itemize

@section Building the packages
@subsection Arch Linux
@verbatim
archLinux-based/
|-- build_pkg.sh
|-- Makefile
|-- packages
|   |-- rserve-sandbox-docker
|   |   |-- .install
|   |   |-- PKGBUILD
|   |   `-- rserve-sandbox-docker.service
|   |-- rserve-sandbox-docker-bin
|   |   |-- .install -> ../rserve-sandbox-docker/.install
|   |   |-- PKGBUILD
|   |   `-- rserve-sandbox-docker.service -> ../rserve-sandbox-docker/rserve-sandbox-docker.service
|   |-- swish
|   |   |-- .install
|   |   |-- PKGBUILD
|   |   `-- swish.service
|   |-- swish-cplint
|   |   |-- .install
|   |   |-- PKGBUILD
|   |   `-- swish-cplint.service
|   `-- swish-cplint-bin
|       |-- .install -> ../swish-cplint/.install
|       |-- PKGBUILD
|       `-- swish-cplint.service -> ../swish-cplint/swish-cplint.service
`-- test
    `-- swish_installer_full_test
@end verbatim

@subsubsection Needed tools
@itemize @bullet
@item
GNU Bash

@item
GNU Make

@item
Gawk

@item
Pacman@footnote{@mybibcite{Pacman}}
@end itemize

@subsubsection Modifications
Once you've made changes you can run @command{$ make}
then change directory into one of the new @code{dest/*.aur} generated
directories and finally run @command{$ makepkg -sri} to install
the package.

You also have the possibility to run the test script 
@file{$ ./test/swish_installer_full_test}. Here is the help page:
@verbatim
Usage: swish_installer_full_test [OPTION]
Full automated install test for the Arch Linux packages in swish-installer

Options are grouped in couples: one excludes the other

Options:
    -b, --binary                use binary packages where available
    -c, --compile               compile packages where available

    -d, --dev                   use development branches where available
    -m, --master                use default branches where available

    -e, --experimental          use swish-installer's dev branch
    -s, --stable                use swish-installer's master branch

    -h, --help                  print this help


Default: --compile --master --stable
Dependencies: git, wget.

Exit status:
 0  if OK,
 1  if an error occurred.

swish_installer_full_test online help: 
<https://frnmst.github.io/swish-installer/swish-installer.html#Help-pages>
Full documentation at: 
<https://frnmst.github.io/swish-installer/swish-installer.html>

Copyright  ©  2017  Franco Masotti.  License GPLv3+: GNU GPL version 3 or
later <http://gnu.org/licenses/gpl.html>.
This  is  free  software: you are free to change and redistribute it.  There
is NO WARRANTY, to the extent  permitted by law.
@end verbatim

@subsection Debian

@subsubsection Needed tools
@itemize @bullet
@item
GNU Bash

@item
GNU Make

@item
<debtools...>

@item
Gawk
@end itemize

@subsubsection Modifications
TODO

@section Help pages
@subsection Rserve sandbox
@verbatim
rserve-sandbox-docker [OPTION]
Docker spec for running Rserve in a sandbox

Only a single option is permitted.
    -h      print this help
    -i      install image and dependencies
    -k      kill the container
    -r      remove the docker image
    -s      start the container

Exit status:
 0  if OK,
 1  some error occurred.

Full documentation at: <https://github.com/frnmst/rserve-sandbox>
@end verbatim

@subsection Rserve sandbox binary
@verbatim
rserve-sandbox-docker [OPTION]
Docker spec for running Rserve in a sandbox

Only a single option is permitted.
    -h      print this help
    -i      load image
    -k      kill the container
    -r      remove the docker image
    -s      start the container

Exit status:
 0  if OK,
 1  some error occurred.

Full documentation at: <https://gitlab.com/frnmst/rserve-sandbox-bin>
@end verbatim

@subsection Cplint on SWISH
@verbatim
swish-cplint [OPTION]
SWI-Prolog for SHaring: a SWI-Prolog web IDE integrated with the cplint suite

Only a single option is permitted.
    -h      print this help
    -i      install dependencies
    -k      kill swish-cplint
    -s      start swish-cplint

Exit status:
 0  if OK,
 1  some error occurred.

Full documentation at: <https://github.com/friguzzi/swish>
and at: <https://github.com/friguzzi/cplint>
@end verbatim

@subsection SWISH
@verbatim
swish [OPTION]
SWI-Prolog for SHaring: a SWI-Prolog web IDE

Only a single option is permitted.
    -h      print this help
    -k      kill swish
    -s      start swish

Exit status:
 0  if OK,
 1  some error occurred.

Full documentation at: <https://github.com/SWI-Prolog/swish>
@end verbatim

@section Compiling this documentation
The source of this documentation is under the @file{doc}
directory.

To be able to compile it, you have to install several tex packages
(for example: @code{texlive-most} and @code{texi2html} if you are using
Arch Linux) that contain the following binaries:

@verbatim
makeinfo
texi2dvi
docbook2html
docbook2pdf
docbook2txt
texi2html
perl
@end verbatim

After running @command{make}, a directory named @file{manual}
is created and you can access the files by opening
@file{index.html} with a browser.

@c ----
@c ----
@c ----
@c ----

@node Thanks
@chapter Thanks
I want to thank the SWI Prolog, Arch Linux and Systemd communities as well the 
authors of the free software used here, which made the creation of these 
packages possible.

I also want to thank Fabrizio Riguzzi which tested the packages and gave me 
advices about them.

@c ----
@c ----
@c ----
@c ----

@node @mybibnode{}
@chapter References

Some quotations reported here are taken directly from the respective web sites.
@*

@itemize @bullet

@mybibitem{Cplint} "A suite of programs for reasoning with probabilistic 
logic programs". See @uref{https://github.com/friguzzi/cplint}
@*

@mybibitem{SWISH} A web browser interface for SWI Prolog to share code. See 
@uref{https://github.com/SWI-Prolog/swish}
for the original version and
@uref{https://github.com/friguzzi/swish}
for the version made by @uref{https://github.com/friguzzi, ,Fabrizio Riguzzi} 
that uses Cplint.
@*

@mybibitem{Rserve} A docker image that enables to use the R and Rserve 
environment in a secure way. See 
@uref{https://github.com/JanWielemaker/rserve-sandbox} for the original version 
made by @uref{https://github.com/JanWielemaker, ,Jan Wielemaker} and
@uref{https://github.com/frnmst/rserve-sandbox/tree/distro-package}
version by @uref{https://github.com/frnmst, ,Franco Masotti}
which is used here. A client to access Rserve from Prolog is also necessary.
See @uref{https://github.com/JanWielemaker/rserve_client}
@*

@mybibitem{R} "R is an integrated suite of software facilities for data 
manipulation, calculation and graphical display". See 
@uref{https://cran.r-project.org/doc/manuals/r-release/R-intro.html}

@mybibitem{Swipl} "SWI-Prolog offers a comprehensive free Prolog environment. 
Since its start in 1987, SWI-Prolog development has been driven by the needs 
of real world applications. SWI-Prolog is widely used in research and 
education as well as commercial applications". See 
@uref{http://www.swi-prolog.org/}
and @uref{https://github.com/SWI-Prolog/swipl-devel}
which is the development version used here.
@*

@mybibitem{Yaourt} "A pacman wrapper with extended features 
and AUR support". To install Yaourt follow the instructions
reported on @uref{https://archlinux.fr/yaourt-en}.
@*

@mybibitem{AUR} "The Arch User Repository (AUR) is a community-driven 
repository for Arch users. It contains package descriptions (PKGBUILDs) that 
allow you to compile a package from source with makepkg and then install it 
via pacman. The AUR was created to organize and share new packages from the 
community and to help expedite popular packages' inclusion into the community 
repository". See @uref{https://aur.archlinux.org/} for the AUR homepage and 
@uref{https://wiki.archlinux.org/index.php/Arch_User_Repository} for a complete 
explanation.
@*

@mybibitem{Parabola} "A fully free, simple, and lightweight
operating system". See @uref{https://parabola.nu}.
@*

@mybibitem{systemd} "systemd is a suite of basic building blocks for a Linux 
system. It provides a system and service manager that runs as PID 1 and starts 
the rest of the system".
See @uref{https://www.freedesktop.org/wiki/Software/systemd/}.
@*

@mybibitem{Docker} "Docker containers wrap a piece of software in a complete 
filesystem that contains everything needed to run: code, runtime, system 
tools, system libraries – anything that can be installed on a server. This 
guarantees that the software will always run the same, regardless of its 
environment". See @uref{https://www.docker.com/}.
@*

@mybibitem{Packages on the AUR} Here follows a list to the AUR packages:
@itemize @minus

@item
SWI Prolog (development version)
@uref{https://aur.archlinux.org/packages/swi-prolog-devel}

@item
Rserve sandbox
@uref{https://aur.archlinux.org/packages/rserve-sandbox-docker/}

@item
Cplint on SWISH
@uref{https://aur.archlinux.org/packages/swish-cplint/}

@item
SWISH
@uref{https://aur.archlinux.org/packages/swish/}

@end itemize
@*

@mybibitem{JavaScript} "JavaScript is a high-level, dynamic, untyped, and
interpreted programming language".
See @uref{https://en.wikipedia.org/wiki/JavaScript}
@*

@mybibitem{Docker root privileges} See
@uref{https://docs.docker.com/engine/security/security/#/docker-daemon-attack-surface}
@*

@mybibitem{Git} "Git is a free and open source distributed version control 
system designed to handle everything from small to very large projects with 
speed and efficiency". See @uref{https://git-scm.com/}
@*

@mybibitem{Graphviz} "Graphviz is open source graph 
visualization software". See @uref{http://graphviz.org/}
@*

@mybibitem{libXinerama} "libXinerama - API for Xinerama extension to X11 
Protocol". See @uref{https://cgit.freedesktop.org/xorg/lib/libXinerama}
@*

@mybibitem{libXpm} "libXpm - X Pixmap (XPM) image file format library".
See @uref{https://cgit.freedesktop.org/xorg/lib/libXpm}
@*

@mybibitem{Bower} "A package manager for the web". See @uref{https://bower.io/}
@*

@mybibitem{curl} "An URL retrieval utility and library".
See @uref{https://curl.haxx.se}
@*

@mybibitem{UnZip} "For extracting and viewing files in .zip archives".
See @uref{http://www.info-zip.org/UnZip.html}
@*

@mybibitem{GNU Bash} "The GNU Bourne Again shell".
See @uref{http://www.gnu.org/software/bash/bash.html}
@*

@mybibitem{Gawk} "GNU version of awk".
See @uref{http://www.gnu.org/software/gawk/}
@*

@mybibitem{Pacman} "A library-based package manager with dependency support".
See @uref{http://www.archlinux.org/pacman/}
@*

@mybibitem{GNU Make} "GNU make utility to maintain groups of programs".
See @uref{http://www.gnu.org/software/make}
@*

@end itemize

@bye

